name: Update Trailhead Stats Manually

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Update trailhead stats'
        required: false
        type: boolean

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: nabondance/trailhead-stats@v1.0.2
        with:
          trailhead-username: 'moleksik'
          display-type: 'card'
          display-file: 'README.md'

