name: Update Trailhead Stats Manually

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Update trailhead stats'
        required: false
        type: boolean

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: nabondance/trailhead-stats@v2
        permissions:
          contents: write
        with:
          trailhead-username: 'moleksik'
          display-type: 'card'
          display-file: 'README.md'
          showSkillTheme: 'winter'
          showSkill: 'visible'
          showCertification: 'detail'
          showBadge: 'hidden'
          showSuperBadge: 'icon'
          showEventBadge: 'icon'
          showStamp: 'icon'
          showCertificationLatest: 'visible'
          showBadgeLatest: 'visible'
          showSuperBadgeLatest: 'visible'
          showEventBadgeLatest: 'visible'
          showStampLatest: 'visible'

